name:                life-game
version:             0.1.0.0
github:              "nwtgck/life-game-haskell"
license:             BSD3
author:              "Ryo Ota"
maintainer:          "nwtgck@gmail.com"
copyright:           "2018 Ryo Ota"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Life Game in Haskell
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/nwtgck/life-game-haskell#readme>

dependencies:
- base >= 4.7 && < 5

#library:
#  source-dirs: src

executables:
  life-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - transformers
    - process
    - random
    - ansi-terminal

tests:
  life-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: []
#    - life-game
